name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          yes | buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: SniperVenom25-APK
          path: bin/*.apk
